FROM hexpm/elixir:1.14.2-erlang-24.3.4.10-ubuntu-jammy-20230126
# RUN apt update && apt -y install zypper
# RUN zypper ar http://download.opensuse.org/update/11.1/ update
RUN apt update && apt install -y curl unzip

ADD ../ /app
WORKDIR /app

RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix deps.get

CMD ["mix", "test"]
