name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.3'
          elixir-version: '1.14.3'
      - run: mix deps.get
      - run: mix test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_env:
          - asdf
          - alpine
          - ubuntu
    steps:
      - uses: actions/checkout@v3
      - name: Run tests in docker-compose
        run: docker-compose up --build --no-log-prefix ${{ matrix.test_env }}
